name: "trojan-horse-hunt"
channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.11.*
  - pip>=20

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - matplotlib==3.10.0
      - pandas==2.2.3
      - seaborn==0.13.2
      - darts==0.33.0
      - scikit-learn==1.6.1
      - autorank==1.3.0  # CD diagram
